version: 2.1
executors:
  my-executor:
    docker:
      - image: circleci/node:13
        auth:
          username: nicodrg
          password: Ndrg100394
jobs:
  build:
    executor: my-executor
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn package cache
          keys: 
            - npm-v1-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn global add node-gyp && yarn install
      - save_cache:
          name: Save Yarn package cache
          key: npm-v1-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn2
  lint:
    executor: my-executor
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn package cache
          keys: 
            - npm-v1-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Analyse code with tslint
          command: yarn lint
      - run:
          name: Format code with prettier
          command: yarn format:check
  test:
    executor: my-executor
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn package cache
          keys: 
            - npm-v1-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Run test with jest
          command: yarn test:ci
workflows:
  version: 2
  integration:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test:
          requires:
            - lint
